var data =
{
    form: {type: "Form",type2: "Oberfläche",
    cards:[
    { name: "ist lang und dünn oder stabförmig" },
    { name: "ist im wesentlichen flach" },
    { name: "ist kugel- oder eiförmig" },
    { name: "ist Kistenförmig oder rechteckig" },
    { name: "Oberfläche ist grösstenteils pelzig oder haarig" },
    { name: "Oberfläche ist warm oder heiss" },
    { name: "Oberfläche ist vorwiegend glatt" },
    { name: "Oberfläche ist vorwiegend rauh" },
    { name: "Oberfläche ist vorwiegend hart" },
    { name: "Oberfläche ist vorwiegend elastisch" },
]},

inhalt: {type: "Inhalt",type2: "Bewegung",
cards:[
    { name: "hat Zähne oder spitze Teile" },
    { name: "mit Rad oder vollständig drehbarem Teil" },
    { name: "mit Gelenk oder beweglichem Teil" },
    { name: "darauf sind Buchstaben, Zeichen oder Zahlen" },
    { name: "bewegt sich selbständig" },
    { name: "bewegt sich selbständig, aber eher langsam" },
    { name: "schwimmt im Wasser oben" },
]},
ort: {type: "Ort",type2: "Zeit",
cards:[
    {name: "kann ich innerhalb von 5 Minuten hierherbringen" },
    {name: "ist nicht im Umkreis von 100 Metern zu finden" },
    {name: "gibt es eher im Wald als in der Stadt" },
    {name: "gibt es häufiger in der Stadt als auf dem Land" },
    {name: "wird eher im Winter als im Sommer verwendet" },
    {name: "wird eher im Sommer als im Winter verwendet" },
    {name: "gab es schon bei den alten Griechen oder Römern" },
    {name: "es gibt jetzt mehr als vor 100 Jahren" },
]},
extra: {type: "Größe",type2: "Gewicht",
cards: [
    { name: "grösser als eine Katze" },
    { name: "passt in ein Gartenhäuschen" },
    { name: "höher als ein 2-stöckiges Reihenhaus" },
    { name: "passt in einen Schuhkarton" },
    { name: "ist 10kg oder leichter" },
    { name: "ist zwischen 10kg und 100kg" },
    { name: "ist 100kg oder schwerer" },
]}}