var engine = {
    cards: [
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Juwelen", subtype: "3" },
        { type: "Juwelen", subtype: "3" },
        { type: "Krone", subtype: "4" },
        { type: "Schwert"},
        { type: "Schwert"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "Truhe", subtype: "1+"},
        { type: "Truhe", subtype: "1+"},
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Juwelen", subtype: "3" },
        { type: "Juwelen", subtype: "3" },
        { type: "Krone", subtype: "4" },
        { type: "Schwert"},
        { type: "Schwert"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "Truhe", subtype: "1+"},
        { type: "Truhe", subtype: "1+"},
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Juwelen", subtype: "3" },
        { type: "Juwelen", subtype: "3" },
        { type: "Krone", subtype: "4" },
        { type: "Schwert"},
        { type: "Schwert"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "MonsterMob"},
        { type: "Truhe", subtype: "1+"},
        { type: "Truhe", subtype: "1+"},
        { type: "Gold", subtype: "2", player:"4+"},
        { type: "Gold", subtype: "2", player:"4+" },
        { type: "Juwelen", subtype: "3" , player:"4+"},
        { type: "Krone", subtype: "4" , player:"4+"},
        { type: "Juwelen", subtype: "3" , player:"4+"},
        { type: "Schwert", player:"4+"},
        { type: "Schwert", player:"4+"},
        { type: "MonsterMob", player:"4+"},
        { type: "MonsterMob", player:"4+"},
        { type: "MonsterMob", player:"4+"},
        { type: "Truhe", subtype: "1+", player:"4+"},
        { type: "Truhe", subtype: "1+"  , player:"4+"},
        { type: "Gold", subtype: "2", player:"5+"},
        { type: "Gold", subtype: "2", player:"5+"},
        { type: "Juwelen", subtype: "3" , player:"5+"},
        { type: "Krone", subtype: "4" , player:"5+"},
        { type: "Juwelen", subtype: "3" , player:"5+"},
        { type: "Schwert", player:"5+"},
        { type: "Schwert", player:"5+"},
        { type: "MonsterMob", player:"5+"},
        { type: "MonsterMob", player:"5+"},
        { type: "MonsterMob", player:"5+"},
        { type: "Truhe", subtype: "1+", player:"5+"},
        { type: "Truhe", subtype: "1+"  , player:"5+"},
        { type: "Gold", subtype: "2", player:"6+"},
        { type: "Gold", subtype: "2", player:"6+"},
        { type: "Juwelen", subtype: "3" , player:"6+"},
        { type: "Krone", subtype: "4" , player:"6+"},
        { type: "Juwelen", subtype: "3" , player:"6+"},
        { type: "Schwert", player:"6+"},
        { type: "Schwert", player:"6+"},
        { type: "MonsterMob", player:"6+"},
        { type: "MonsterMob", player:"6+"},
        { type: "MonsterMob", player:"6+"},
        { type: "Truhe", subtype: "1+", player:"6+"},
        { type: "Truhe", subtype: "1+", player:"6+"},
        { type: "Höhle", height:150, text:"MonsterMob dreht.", player:"4+" },
        { type: "Höhle", height:150, text:"MonsterMob dreht.", player:"5+" },
        { type: "Höhle", height:150, text:"MonsterMob dreht.", player:"6+" },
        { type: "Höhle", height:150, text:"MonsterMob zieht genau 1." },
        { type: "Höhle", height:150, text:"MonsterMob zieht 1 mehr." },
        { type: "Höhle", height:150, text:"MonsterMob wütend. Schwerter nutzlos." },
        { type: "Höhle", height:150, text:"2 Spieler an der Truhe.", player:"8+"  },
        { type: "Höhle", height:150, text:"MonsterMob greift x Spieler an.", player:"7+"  },
    ],
    shuffle: function() {
        for (var j, x, i = this.cards.length; i; j = Math.floor(Math.random() * i), x = this.cards[--i], this.cards[i] = this.cards[j], this.cards[j] = x);
        return this.cards;
    },
    init: function(game) {

    }
}
