var engine = {
    cards: [
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "1" },
        { type: "Schatz", subtype: "1" },
        { type: "Schwert" },
        { type: "Schwert"},
        { type: "Schwert" },
        { type: "Schwert" },
        { type: "Schwert"},
        { type: "Schwert" },
        { type: "Schwert" },
        { type: "Schwert"},
        { type: "Schwert" },
        { type: "Schwert" },
        { type: "Schwert"},
        { type: "Mob" },
        { type: "Mob"},
        { type: "Mob" },
        { type: "Mob" },
        { type: "Mob"},
        { type: "Mob" },
        { type: "Mob" },
        { type: "Mob"},
        { type: "Mob" },
        { type: "Mob" },
        { type: "Mob"},
        { type: "Tür" },
        { type: "Tür" },
        { type: "Tür" },
        { type: "Tür" },
        { type: "Tür" },
        { type: "Höhle", height:150, text:"Der MonsterMob dreht einmalig sofort die Richtung." },
        { type: "Höhle", height:150, text:"Der MonsterMob zieht in seiner Bewegung dauerhaft 1 Feld weiter" },
        { type: "Höhle", height:150, text:"Der MonsterMob ist in Rage. Schwerter sind nutzlos. Alle Schätze gehen beim Angriff verloren." },
        { type: "Höhle", height:150, text:"Die beiden Spieler die am nächsten an der Tür sitzen, dürfen ihre Schätze rausbringen." },
        { type: "Höhle", height:150, text:"Die beiden Spieler, die am nächsten am MonsterMob sitzen werden angegriffen." },
        { type: "Höhle", height:150, text:"Die MonsterMob zieht in jeder Runde genau ein Feld wetier. (Alle Monsterkarten sind nutzlos.)" },
        { type: "Höhle", height:150, text:"Nebenausgang: Jeder Spieler darf die oberste Karte sein Ablagestapels rausbringen." },
    ],
    shuffle: function() {
        for (var j, x, i = this.cards.length; i; j = Math.floor(Math.random() * i), x = this.cards[--i], this.cards[i] = this.cards[j], this.cards[j] = x);
        return this.cards;
    },
    init: function(game) {

    }
}
