var engine = {
    cards: [
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "4" },
        { type: "Schwert", subtype: "1"},
        { type: "Schwert", subtype: "1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-2"},
        { type: "Tür", subtype: "1"},
        { type: "Heiltrank", subtype: "X"},
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "4" },
        { type: "Schwert", subtype: "1"},
        { type: "Schwert", subtype: "1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-2"},
        { type: "Tür", subtype: "1"},
        { type: "Heiltrank", subtype: "X"},
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "2" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "3" },
        { type: "Schatz", subtype: "4" },
        { type: "Schwert", subtype: "1"},
        { type: "Schwert", subtype: "1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-1"},
        { type: "MonsterMob", subtype: "-2"},
        { type: "Tür", subtype: "1"},
        { type: "Heiltrank", subtype: "X"  },
        { type: "Schatz", subtype: "2", player:"4+"},
        { type: "Schatz", subtype: "2", player:"4+" },
        { type: "Schatz", subtype: "3" , player:"4+"},
        { type: "Schatz", subtype: "4" , player:"4+"},
        { type: "Schatz", subtype: "3" , player:"4+"},
        { type: "Schwert", subtype: "1", player:"4+"},
        { type: "Schwert", subtype: "1", player:"4+"},
        { type: "MonsterMob", subtype: "-1", player:"4+"},
        { type: "MonsterMob", subtype: "-1", player:"4+"},
        { type: "MonsterMob", subtype: "-2", player:"4+"},
        { type: "Tür", subtype: "1", player:"4+"},
        { type: "Heiltrank", subtype: "X"  , player:"4+"},
        { type: "Schatz", subtype: "2", player:"5+"},
        { type: "Schatz", subtype: "2", player:"5+"},
        { type: "Schatz", subtype: "3" , player:"5+"},
        { type: "Schatz", subtype: "4" , player:"5+"},
        { type: "Schatz", subtype: "3" , player:"5+"},
        { type: "Schwert", subtype: "1", player:"5+"},
        { type: "Schwert", subtype: "1", player:"5+"},
        { type: "MonsterMob", subtype: "-1", player:"5+"},
        { type: "MonsterMob", subtype: "-1", player:"5+"},
        { type: "MonsterMob", subtype: "-2", player:"5+"},
        { type: "Tür", subtype: "1", player:"5+"},
        { type: "Heiltrank", subtype: "X"  , player:"5+"},
        { type: "Schatz", subtype: "2", player:"6+"},
        { type: "Schatz", subtype: "2", player:"6+"},
        { type: "Schatz", subtype: "3" , player:"6+"},
        { type: "Schatz", subtype: "4" , player:"6+"},
        { type: "Schatz", subtype: "3" , player:"6+"},
        { type: "Schwert", subtype: "1", player:"6+"},
        { type: "Schwert", subtype: "1", player:"6+"},
        { type: "MonsterMob", subtype: "-1", player:"6+"},
        { type: "MonsterMob", subtype: "-1", player:"6+"},
        { type: "MonsterMob", subtype: "-2", player:"6+"},
        { type: "Tür", subtype: "1", player:"6+"},
        { type: "Heiltrank", subtype: "X"  , player:"6+"},
        { type: "Höhle", height:150, text:"MonsterMob dreht." },
        { type: "Höhle", height:150, text:"MonsterMob dreht." },
        { type: "Höhle", height:150, text:"MonsterMob dreht." },
        { type: "Höhle", height:150, text:"MonsterMob zieht genau 1." },
        { type: "Höhle", height:150, text:"MonsterMob zieht 1 mehr." },
        { type: "Höhle", height:150, text:"MonsterMob wütend. Schwerter nutzlos." },
        { type: "Höhle", height:150, text:"2 Spieler an der Tür." },
        { type: "Höhle", height:150, text:"MonsterMob greift x Spieler an." },
    ],
    shuffle: function() {
        for (var j, x, i = this.cards.length; i; j = Math.floor(Math.random() * i), x = this.cards[--i], this.cards[i] = this.cards[j], this.cards[j] = x);
        return this.cards;
    },
    init: function(game) {

    }
}
