var cards = [
    {type:"Schatz",subtype:"A",count: 4},
    {type:"Schatz",subtype:"B",count: 4},
    {type:"Schatz",subtype:"C",count: 4},
    {type:"Schatz",subtype:"D",count: 4},
    {type:"Herz",subtype:"A",count: 2},
    {type:"Herz",subtype:"B",count: 2},
    {type:"Tür",subtype:"A",count: 2},
    {type:"Tür",subtype:"B",count: 2},
    {type:"Mob",subtype:"A",count: 4,dark:"dark"},
    {type:"Mob",subtype:"B",count: 4,dark:"dark"},
    {type:"Mob",subtype:"C",count: 4,dark:"dark"},
    {type:"Mob",subtype:"D",count: 4,dark:"dark"},
    {type:"Biss",subtype:"A",count: 3,dark:"dark"},
    {type:"Biss",subtype:"B",count: 3,dark:"dark"},
    {type:"Biss",subtype:"C",count: 3,dark:"dark"},
    {type:"Dieb",subtype:"A",count: 3,dark:"dark"},
    {type:"Dieb",subtype:"B",count: 3,dark:"dark"},
    {type:"Dieb",subtype:"C",count: 3,dark:"dark"},
]