var dataform = [
    { type: "Form", name: "mindestens so gross wie eine Katze" },
    { type: "Form", name: "kleiner als ein Esstisch" },
    { type: "Form", name: "grösser als ein Haus" },
    { type: "Form", name: "passt in eine quadratische Kiste mit 1 Meter Seitenlänge" },
    { type: "Form", name: "ist lang und dünn oder stabförmig" },
    { type: "Form", name: "ist im wesentlichen flach" },
    { type: "Form", name: "ist im wesentlichen röhrenförmig" },
    { type: "Form", name: "ist kugel- oder eiförmig" },
    { type: "Form", name: "ist Kistenförmig oder rechteckig" },
    { type: "Form", name: "steht mit 4 Berührungspunkten auf dem Boden" },
    { type: "Form", name: "mit vielen Unregelmässigkeiten (Noppen, Dellen, Nasen)" },
    { type: "Form", name: "mit Gelenk oder beweglichem Teil" },
    { type: "Form", name: "mit Verzweigungen, Gabelungen, Asten, Extremitäten" },
    { type: "Form", name: "ist spitz, man kann sich damit in den Finger stechen" },
    { type: "Form", name: "aus mehreren Teilen, evtl. miteinander verbunden" },
    { type: "Form", name: "'Vorne' und 'hinten' sind hier kaum unterscheidbar" },
    { type: "Form", name: "mit Loch, durch das man durchschauen kann" },
    { type: "Form", name: "mit Rad oder vollständig beweglichem Teil" },
];

var datainhalt = [
    { type: "Inhalt", name: "ist 10kg oder schwerer" },
    { type: "Inhalt", name: "ist 10kg oder leichter" },
    { type: "Inhalt", name: "hat Hörner oder Zähne" },
    { type: "Inhalt", name: "enthält Zähflüssiges, Schleimiges oder Klebriges" },
    { type: "Inhalt", name: "hat Haare" },
    { type: "Inhalt", name: "hat innen Weichteile" },
    { type: "Inhalt", name: "hat ein Gehirn, Mechanik oder CPU" },
    { type: "Inhalt", name: "enthält Kugelförmiges" },
    { type: "Inhalt", name: "ist steif, kann brechen" },
    { type: "Inhalt", name: "besteht teilweise aus Tuch oder Stoff" },
    { type: "Inhalt", name: "enthält Glas oder durchsichtiges Material" },
    { type: "Inhalt", name: "enthält Stein" },
    { type: "Inhalt", name: "enthält Holz oder Äste" },
    { type: "Inhalt", name: "besteht aus Papier, Karton oder Stroh" },
    { type: "Inhalt", name: "darauf sind manchmal Buchstaben, Zeichen oder Zahlen" },
];
var dataort = [
    { type: "Ort", name: "ist oft im Büro" },
    { type: "Ort", name: "gibt es bei mir zu Hause" },
    { type: "Ort", name: "kann ich innerhalb von 5 Minuten hierherbringen" },
    { type: "Ort", name: "gibt es im Supermarkt" },
    { type: "Ort", name: "tragen Menschen bei sich" },
    { type: "Ort", name: "wird meist im Winter verwendet" },
    { type: "Ort", name: "haben alle hier schon in der Hand gehabt" },
    { type: "Ort", name: "wird meist im Sommer verwendet" },
    { type: "Ort", name: "ist nicht im Umkreis von 80 Metern zu finden" },
    { type: "Ort", name: "in diesem Land gibt es sehr viele" },
    { type: "Ort", name: "gibt es auch im Wald oder Feld" },
    { type: "Ort", name: "gab es schon bei den alten Griechen oder Römern" },
    { type: "Ort", name: "gibt es in einem Wild West Film" },
    { type: "Ort", name: "gibt es in der Stadt" },
    { type: "Ort", name: "es gibt mehr davon als vor 100 Jahren" },
];
var dataextra = [
    { type: "Bewegung", name: "schwimmt im Wasser oben" },
    { type: "Bewegung", name: "ist praktisch unbeweglich" },
    { type: "Bewegung", name: "kann von eimen Menschen bewegt werden" },
    { type: "Bewegung", name: "kann sich selbständig bewegen" },
    { type: "Bewegung", name: "fliegt oder schwebt" },
    { type: "Bewegung", name: "hat Räder zur Bewegung" },
    { type: "Bewegung", name: "kann in der Strassenbahn transportiert werden" },
    { type: "Bewegung", name: "bewegt sich auf 2 Beinen oder Rädern" },
    { type: "Bewegung", name: "bewegt sich sehr langsam" },
    { type: "Bewegung", name: "bewegt sich mit Elektrizität oder Brennstoff" },
];