var data2 = {
    akt: 2,
    initcards: [
        { name: "Gang", Aktion: "", flavour: "Jane: 'Was war das für ein Geräusch?'", hor: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Prof. Hampton ist vermutlich schon tot.' Jane: 'Nein, er lebt noch.'", hor: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Hier können wir rasten.'", hor: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Hier ist erst vor kurzem jemand vorbeigekommen.'", ver: true },
        { name: "Gang", Aktion: "", flavour: "Jane: 'Wir brauchen mehr Wasser zum Trinken.'", ver: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Wir sollten umkehren.'", ver: true },
        { name: "Gang", Aktion: "", flavour: "Jane: 'DIeser Gang wurd künstlich angelegt..'", ver: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Hier geht es nicht weiter.'", ver: true, hor: true },
        { name: "Gang", Aktion: "", flavour: "Jane: 'Hier sind sehr ungewöhnliche Schriftzeichen.'", ver: true, hor: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Pause.'", ver: true, hor: true },
        { name: "Gang", Aktion: "", flavour: "Jack: 'Pause.'", ver: true, hor: true },
        { name: "Rucksack", Aktion: "Du findest einen alten Rucksack. Nimm die Inventarkarte Rucksack hinzu.", ver: true, imgclass: "symbol" },
        { name: "Geheimgang", Aktion: "Wenn man eine Fackel besitzt, kann man von diesem Geheimgang direkt zu einem anderen Geheimgang ziehen. Die Fackel darf man behalten.", hor: true, info: "info" },
        { name: "Geheimgang", Aktion: "Wenn man eine Fackel besitzt, kann man von diesem Geheimgang direkt zu einem anderen Geheimgang ziehen. Die Fackel darf man behalten.", hor: true, info: "info" },
        { name: "Geheimgang", Aktion: "Wenn man eine Fackel besitzt, kann man von diesem Geheimgang direkt zu einem anderen Geheimgang ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Geheimgang", Aktion: "Wenn man eine Fackel besitzt, kann man von diesem Geheimgang direkt zu einem anderen Geheimgang ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Zugang Fluss", Aktion: "Hier fliesst ein unterirdischer Fluss. Ihr könnt euch von ihn nach rechts und unten zu einem anderen Zugang Fluss bringen lassen.", info: "info" },
        { name: "Zugang Fluss", Aktion: "Hier fliesst ein unterirdischer Fluss. Ihr könnt euch von ihn nach rechts und unten zu einem anderen Zugang Fluss bringen lassen.", info: "info" },
        { name: "Zugang Fluss", Aktion: "Hier fliesst ein unterirdischer Fluss. Ihr könnt euch von ihn nach rechts und unten zu einem anderen Zugang Fluss bringen lassen.", info: "info" },
        { name: "Zugang Fluss", Aktion: "Hier fliesst ein unterirdischer Fluss. Ihr könnt euch von ihn nach rechts und unten zu einem anderen Zugang Fluss bringen lassen.", info: "info" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", ver: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", ver: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", hor: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", hor: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", hor: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Eine Fackel steckt in der Felswand.", hor: true, imgclass: "symbol" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Kannibalen", Aktion: "Die Kannibalen stehen hier Wache. Habt ihr den Schrunpfkopf bei euch, lassen sie euch vorbeiziehen. Ansonsten könnt ihr das Feld nicht betreten.", info: "problem" },
        { name: "Gesteinswand", Aktion: "Hier ist massiver Fels. Du kannst dieses Feld nicht betreten.", info: "problem" },
        { name: "Gesteinswand", Aktion: "Hier ist massiver Fels. Du kannst dieses Feld nicht betreten.", info: "problem" },
        { name: "Schrumpfkopf", Aktion: "Ihr findet einen Schrumpfkopf der Kannibalen.", hor: true, imgclass: "symbol"},
        { name: "Dynamit", Aktion: "Du findest einen versteckten Vorrat an Dynamit und kannst damit eine Gesteinswand sprengen. Lege dazu das Dynamit und eine Fackel von einem Nachbarfeld aus ohne Wand dazwischen auf die Gesteinswand.", imgclass: "symbol"},
        { name: "Artefakt", Aktion: "Du findest ein Artefakt einer unbekannten Zivilisation. ", imgclass: "symbol", hor: true },
        { name: "Artefakt", Aktion: "Du findest ein Artefakt einer unbekannten Zivilisation. ", imgclass: "symbol", hor: true },
        { name: "Artefakt", Aktion: "Du findest ein Artefakt einer unbekannten Zivilisation. ", imgclass: "symbol", ver: true },
        { name: "Spinne", Aktion: "Riesige Spinnen blockieren hier den Durchgang. Du kannst nicht geradeausgehen, sondern nur abbiegen. Lege eine Fackel hier ab, um die Spinne zu verbrennen.", info: "problem"},
        { name: "Spinne", Aktion: "Riesige Spinnen blockieren hier den Durchgang. Du kannst nicht geradeausgehen, sondern nur abbiegen. Lege eine Fackel hier ab, um die Spinne zu verbrennen.", info: "problem"},
        { name: "Spinne", Aktion: "Riesige Spinnen blockieren hier den Durchgang. Du kannst nicht geradeausgehen, sondern nur abbiegen. Lege eine Fackel hier ab, um die Spinne zu verbrennen.", info: "problem"},
        { name: "Spinne", Aktion: "Riesige Spinnen blockieren hier den Durchgang. Du kannst nicht geradeausgehen, sondern nur abbiegen. Lege eine Fackel hier ab, um die Spinne zu verbrennen.", info: "problem" },
        { name: "Spinne", Aktion: "Riesige Spinnen blockieren hier den Durchgang. Du kannst nicht geradeausgehen, sondern nur abbiegen. Lege eine Fackel hier ab, um die Spinne zu verbrennen.", info: "problem" },
        { name: "Verlaufen", info: "event", Aktion: "Ihr habt euch komplett verlaufen. Legt alle direkt benachbarten Feldkarten unter den Nachziehstapel. (Das gilt nicht für Aktionskarten!) ", info: "problem" },
        { name: "Felsfalle", info: "event", Aktion: "Lass die Karte aus Kopfhöhe auf den Tisch fallen. Landet Sie mit dieser Seite nach oben, löst ihr eine Falle aus. Legt die Karte auf das Feld eurer Figur und zieht mit eurere Figur innerhalb von 5 Sekunden auf ein benachbartes erreichbares Feld. Dieses Feld mit nich mehr betretbar.", info: "problem" },
        { name: "Überfall", order: "event", Aktion: "Jack kommt von einer Suche zurück und Jane ist verschwunden. Er findet Spuren eines Kampfes. Lege Janes Inventarkarte zur Seite.Verwende in Akt 3 eine Aktionskarte mit 'Jane'", task: true },
    ],
    initEvents: [
    ],
    initActions: [
        { name: "Jäger", order: "accessibility", orderText: "Jäger",Aktion: "Der Jäger Stoephasius klaut dir alle Artefakte und bringt sie zur gegenüberliegenden Aktionskarte. Mit der Pistole kannst du sie ihm dort abnehmen. Er ist auf der Suche nach der geheimen Schatzkammer der Kannibalen.",  task: true },
        { name: "Leiche", order: "accessibility",orderText: "Jäger", Aktion: "Jack findet eine halbverweste Leiche. Es ist der Geschäftspartner des Jägers Stoephasius. Er wurde offensichtlich von hinten erschossen. Jack findet einen Brief, der beweist, dass Stoephasius für den Tod von Jacks Frau verantwortlich ist. Jane ist entsetzt. 1 Bonuspunkt.", task: true },
        { name: "Jäger", order: "accessibility",orderText: "Jäger", Aktion: "Der Jäger Stoephasius wurde von Kannibalen gefangen genommen und wird in ihr Dorf transportiert. Mit der Pistole kannst du ihn retten. Aus Dankbarkeit erhälst du einen Bonuspunkt. Ansonsten wird er von den Kannibalen getötet.",  task: true },
        { name: "Gefangen", order: "build", orderText: "Jack",Aktion: "Jack wird von den Kannibalen überrascht und gefangen. Jane muss den Kannibalen den Schrumpfkopf geben, dann lassen sie Jack frei. Bis dahin kannst du Jacks Inventarkarte nicht verwenden. Ist auch Jane gefangen, dann ist das Abenteuer nun beendet.", task: true },

        { name: "Abendrot", order: "build",orderText: "Jack", Aktion: "Im Sonnenuntergang verliebt sich Jack in Jane. Er weis nicht, ob Sie seine Liebe erwidert. Er hat das Gefühl, schon viele Abenteuer mit Jane erlebt zu haben. Schau dir die nächsten drei Karten vom Stapel an und lege Sie gemeinsam zurück oder unter den Stapel.", task: true },
        { name: "Minenfahrt", order: "home", orderText: "Ausgang", Aktion: "Wenn ihr den Weg zum 'Tal der Kannibalen' kennt, alle 4 Höhlen im Spielplan gefunden sind und ihr eine Fackel besitzt, könnt ihr mit einer Lore in das 'Tal der Kannibalen' fahren. Dabei musst du die Fackel abgeben. Verwende in Akt 2 eine Aktionskarte mit 'Mine'", task: true },

        { name: "Diamantenmine", order: "select-all", orderText: "Mine", Aktion: "Mit der Fackel findest du in der dunklen Mine große Diamanten. Wenn du Sie herausholst, verlierst du die Fackel. Du erhälst einen Bonuspunkt.",  imgclass: "symbol", task: true },
        { name: "Altar", order: "select-all", orderText: "Mine", Aktion: "Ihr findet einen geheimen Zeremonienaltar der Kannibalen. Von dort könnt ihr euch 2 Macheten mitnehmen.", imgclass: "Machete", task: true },
        { name: "Schlangengrube", order: "select-all", orderText: "Mine", Aktion: "In einer Höhle seid ihr von Schlangen umzingelt. Gebt eine Fackel ab oder legt 3 Dinge vom Inventar auf ihre Felder zurück oder in den Vorrat, um den Schlangen zu entkommen. Habt ihr beides nicht, sterbt ihr in der Schlangengrube.",  task: true },


        { name: "Königin", order: "gesture", orderText: "Jane", Aktion: "Jane wird von den Kannibalen als Dschungelkönigin verehrt. Lege mit der Fackel ein Feuer, dann kann Jane unbemerkt fliehen. Jane erzählt dir von einer geheimen Schatzkammer der Kannibalen. Die Fackel geht in den Vorrat.", task: true },
        { name: "Befreit", order: "gesture", orderText: "Jane", Aktion: "Der Jäger Stoephsius hat Jane aus dem Dorf der Kannibalen befreit, dabei hat er allerdings mehrere Kannibalen getötet. Der Schrumpfkopf schützt euch nun nicht mehr vor den Kannibalen. Du kannst Janes Inventarkarte nun wieder verwenden.", task: true },
        { name: "Schatzkammer", order:"exit-to-app", orderText: "Ende", Aktion: "Ihr habt die Schatzkammer der Kannibalen gefunden. Wenn ihr die 3 Artefakte hier ablegt und Jack und Jane dabei sind, könnt ihr die Tür zur Schatzkammer öffnen. Darin findet ihr ein Geheimnis und beendet die Partie erfolgreich.", task: true },
        { name: "Höhlentor", order:"exit-to-app", orderText: "Ende", Aktion: "Ihr habt das im Tagebuch beschriebene Höhlentor gefunden. Wenn ihr die 3 Artefakte hier ablegt, könnt ihr das Tor öffnen und erreicht den 3. Akt.", task: true },
    ],
    start: {name: "Akt II", task: true,
    Aktion: "Ihr erreicht das 'Tal der Kannibalen' am Fuße eines Vulkanberges. Ihr findet den Höhleneingang in den Berg und tretet ein. In der Höhle ist ein dämmriges Licht und viele abzweigende Gänge."},
    secrets: [
        {level: 1, text: "Jane: 'Danke Jack, dass wir es bis hier geschafft haben. Ich schulde dir ein paar Hintergründe: Prof. Hampton ist mein Vater. Meine Mutter ist bei der Geburt gestorben. Vater sucht schon seit vielen Jahren nach dem untergegangenen Reich von Atlantis. Von seiner letzten Expedition hier in den Dschungel ist er nicht mehr zurückgekehrt. Ich spüre aber, dass er noch lebt. Lass uns weitersuchen.' Jack sieht plötzlich ein helles Licht auf sich zukommen. In einem Zeitstrudel wird er drei Tage in die Vergangeheit zurückkatapultiert. Er sitzt mit Jane in dem abgestürzten Flugzeug und beginnt das Abenteuer (mit 2 Sternen) von vorne. Jack und Jane können sich nicht an die vorherigen Ereignisse erinnern."},
        {level: 2, text: "Jane: 'Ich kann dir nun vertrauen und dir mein Geheimnis erzählen. Ich besitze eine besondere Gabe. Ich kann die Zeit um bis zu 3 Tage zurückdrehen. Dabei vergesse ich selbst das Meiste und kann mich nur an kleine Informationen erinnern. Wir haben dieses Abenteuer vermutlich schon viele Male durchlebt. Deswegen glaubst du auch, mich schon so lange zu kennen. Wir werden dieses Abenteuer wiederholen, bis ich weis, wo mein Vater hingegangen ist. Tut mir leid, dass du das alles mitmachen musst.' Erneut kommt der Zeitstrudel auf Jack und Jane zu und verschluckt beide. Sie finden sich ohne Erinnerung im abgestürzten Flugzeug wieder. Das Abenteuer beginnt erneut (mit 3 Sternen)."},
        {level: 3, text: "Jane findet einen versteckten Brief ihres Vaters: 'Liebe Jane, wenn du diese Zeilen liest, bin ich bereits auf dem Weg nach Atlantis. Mit Hilfe dieser Schatzkammer konnte ich den genauen Ort ermittlen. Ich habe deine Mutter Mahara vor 25 Jahren kennengelernt. Nach einer gemeinsamen Nacht war Sie verschwunden. Ein Jahr später kam Sie mit dir im Arm zu mir, und bat mich dich aufzuziehen. Sie ist eine der letzten Überlebenden von Atlantis und du bist die letzte Tochter von Atlantis. Folge mir nun (in Teil 2) und komm in deine eigentliche Heimat. Die Kannibalen sind eigentlich friedlich und bewachen den Zugang zur Schatzkammer und den Eingang zum letzten Ort von Atlantis'. VOr Freude fallen sich Jack und Jane in die Arme und es gibt einen langen intensiven Liebeskuss. THE END."},
    ]
 }