var data1 = {
    akt: 1,
    initcards: [
        { name: "Weg", Aktion: "", flavour: "Jane: 'Ob ich ihm von meiner Suche erzählen kann?'", hor: true },
        { name: "Weg", Aktion: "", flavour: "Jane: 'Was für eine schöne Pflanze.' Jack: 'Vorsicht, die ist giftig.'", ver: true },
        { name: "Weg", Aktion: "", flavour: "Jane: 'Jack hat ein düsteres Geheimnis, das spüre ich.'", ver: true },
        { name: "Weg", Aktion: "", flavour: "Jack: 'Was suchen wir hier eigentlich?'", ver: true },
        { name: "Weg", Aktion: "", flavour: "Jack: 'Ich brauche einen Whisky.'", ver: true, hor: true },
        { name: "Weg", Aktion: "", flavour: "Jane: 'Puuh, diese Luft bringt mich um.'", ver: true },
        { name: "Weg", Aktion: "", flavour: "Jack: 'Wer hat wohl meinen Bezintank manipuliert?'", hor: true },
        { name: "Weg", Aktion: "", flavour: "Jack: 'Hier können wir rasten.'", hor: true },
        { name: "Weg", Aktion: "", flavour: "Jane: 'Hier waren wir doch schon mal.'", hor: true },
        { name: "Weg", Aktion: "", flavour: "Jane: Prof. Hampton ist ein berühmter Archeologe.", hor: true },
        { name: "Weg", Aktion: "", flavour: "Jane: 'Ist das der richtige Weg?'", hor: true, ver: true },
        { name: "Tempel", Aktion: "Ihr findet eine alte Tempelruine mit unbekannten Schriftzeichen.", hor: false, ver: true },
        { name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.", ver: true, imgclass: "symbol" },
        { name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.", hor: true, ver: true, imgclass: "symbol" },
        { name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.", hor: true, imgclass: "symbol" },
        { name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.", hor: true, imgclass: "symbol" },
        { name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit über Wände auf ein offenes Feld springen. Lege die Liane dann in den Vorrat.", hor: true, imgclass: "symbol" },
        { name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit über Wände auf ein offenes Feld springen. Lege die Liane dann in den Vorrat.", hor: true, imgclass: "symbol" },
        { name: "Höhle", Aktion: "Wenn man die Fackel besitzt, kann man von dieser Höhle direkt zu einer anderen Höhlenkarte ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Höhle", Aktion: "Wenn man die Fackel besitzt, kann man von dieser Höhle direkt zu einer anderen Höhlenkarte ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Höhle", Aktion: "Wenn man die Fackel besitzt, kann man von dieser Höhle direkt zu einer anderen Höhlenkarte ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Höhle", Aktion: "Wenn man die Fackel besitzt, kann man von dieser Höhle direkt zu einer anderen Höhlenkarte ziehen. Die Fackel darf man behalten.", ver: true, info: "info" },
        { name: "Hängebrücke", info: "problem", Aktion: "Über eine tiefe Schlucht spannt sich eine Hängebrücke. Du kannst den Ort nur geradeaus überqueren. Wenn du deinen Zug hier beendest, kannst du auch abbiegen." },
        { name: "Hängebrücke", info: "problem", Aktion: "Über eine tiefe Schlucht spannt sich eine Hängebrücke. Du kannst den Ort nur geradeaus überqueren. Wenn du deinen Zug hier beendest, kannst du auch abbiegen." },
        { name: "Boot", Aktion: "Mit dem Boot kannst du dem See überqueren oder auf dem Fluß fahren.", hor: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Mit einer Fackel kann man von einer Höhle zu einer anderen ziehen. Die Fackel darf man dabei behalten.", ver: true, imgclass: "symbol" },
        { name: "Fackel", Aktion: "Mit einer Fackel kann man von einer Höhle zu einer anderen ziehen. Die Fackel darf man dabei behalten.", ver: true, imgclass: "symbol" },
        { name: "Pistole", Aktion: "Die Pistole ist alt und hat nur noch eine Kugel.", hor: true, imgclass: "symbol" },
         { name: "See", Aktion: "Nur mit dem Boot kannst du den See betreten oder überqueren.", info: "problem" },
        { name: "See", Aktion: "Nur mit dem Boot kannst du den See betreten oder überqueren.", info: "problem" },
        { name: "Tagebuch", Aktion: "Ihr findet das Tagebuch von Professor Hampton. Er sucht das geheime 'Tal der Kannibalen'. Finde den Tempel oder die versteckte Inschrift, um den Weg dorhin zu entschlüsseln.", imgclass: "symbol" },
        { name: "Gegengift", Aktion: "Das Gegengift schützt dich vor einer Schlange. Lege das Gegengift dazu auf die Schlange. ", hor: true, imgclass: "symbol" },
        { name: "Gegengift", Aktion: "Das Gegengift schützt dich vor einer Schlange. Lege das Gegengift dazu auf die Schlange.", hor: true, imgclass: "symbol" },
        { name: "Gegengift", Aktion: "Das Gegengift schützt dich vor einer Schlange. Lege das Gegengift dazu auf die Schlange.", hor: true, imgclass: "symbol" },
        { name: "Schrumpfkopf", order: "star", Aktion: "Ihr findet einen alte verfallenen Brunnen. Wenn ihr in diesen mit einer Fackel hinabsteigt, findet ihr darin einen Schrumpfkopf der Kannibalen. Die Fackel müsst ihr dann abgeben.", imgclass: "symbol"},
        { name: "Affenhorde", Aktion: " Mit der Pistole kannst du Affenhorde verjagen. Lege die Pistole hier ab. Ansonsten klauen die Affen euch einen Gegenstand. Lege einen Gegenstand aus dem Inventar in den Vorrat.", ver: true, info: "problem" },
        { name: "Affenhorde", Aktion: " Mit der Pistole kannst du Affenhorde verjagen. Lege die Pistole hier ab. Ansonsten klauen die Affen euch einen Gegenstand. Lege einen Gegenstand aus dem Inventar in den Vorrat.", ver: true, info: "problem" },
        { name: "Affenhorde", Aktion: " Mit der Pistole kannst du Affenhorde verjagen. Lege die Pistole hier ab. Ansonsten klauen die Affen euch einen Gegenstand. Lege einen Gegenstand aus dem Inventar in den Vorrat.", ver: true, info: "problem" },
        { name: "Affenhorde", Aktion: " Mit der Pistole kannst du Affenhorde verjagen. Lege die Pistole hier ab. Ansonsten klauen die Affen euch einen Gegenstand. Lege einen Gegenstand aus dem Inventar in den Vorrat.", hor: true, info: "problem" },
        { name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beißt dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", info: "problem", hor: true },
        { name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beißt dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", info: "problem", ver: true },
        { name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beißt dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", info: "problem", ver: true },
        { name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beißt dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", info: "problem", ver: true },
        { name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beißt dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", info: "problem", hor: true  },
    ],
    initActions: [
        { name: "Inschrift", order: "announcement", Aktion: "Eine Steininschrift ist hinter Dschungelpflanzen verborgen. Lege eine Machete hier ab, um die Inschrift freizulegen. Mit dem Tagebuch könnt ihr den Text übersetzen. Er verrät euch die Position des 'Tal der Kannibalen'", task: true },
       { name: "Traum", order: "announcement", Aktion: "Jane hat einen mysteriösen Traum. Im Tempel findet Sie mit der Fackel und dem Tagebuch den Weg zum Tal der Kanibalen. Legt die Fackel und das Tagebuch im Tempel ab, dann kennt ihr den Weg zum 'Tal der Kannibalen'.", task: true },
        { name: "Lager", Aktion: "Du findest ein verlassenes Lager. Du kannst bis zu 2 Dinge aus dem Vorrat auf passende leere Karten legen. (z.B.: Liane auf Lianenkarte)", task: true },
        { name: "Explosion", Aktion: "In der Ferne hört ihr ein riesige Explosion. Das Flugzeug ist explodiert. Nehmt die Startkarte in der Spielmitte aus dem Spiel.", task: true },

        { name: "Tierfalle", Aktion: "Jacks Bein verletzt sich in einer Tierfalle des Jägers Stoephasius. Du kannst bis zu einem anderen Eckfeld pro Zug nur 3 Felder weit ziehen. Verwende in Akt 2 eine Aktionskarte mit 'Jäger'", task: true },
        { name: "Überfall", order: "star", Aktion: "Jack kommt ins Lager zurück und Jane ist verschwunden. Er findet Spuren eines Kampfes und Pfeile der Kannibalen. Lege Janes Inventarkarte zur Seite.Verwende in Akt 2 eine Aktionskarte mit 'Jane'", task: true },
        { name: "Whiskykiste", order: "star", Aktion: "Jack hat Alkoholprobleme, weil seine Frau vor 3 Jahren in einem Hinterhalt erschossen wurde. Falls du in den letzten 24 Stunden keinen Alkohol getrunken hast, kann sich auch Jack beherrschen. Verwende dann'Jack' in Akt 2. Ansonsten säuft er sich voll und du verlierst einen Gegenstand.", task: true },
        { name: "Alligator", order: "star", Aktion: "Jane wird von einem Alligator angegriffen, aber im letzten Moment vom Jäger Stoephasius gerettet. Er will sich euch anschliessen, aber Jane weist ihn wütend zurück. Stoephasius verlässt euch mit den Worten: 'Das wird euch noch leid tun.' Akt 2 mit 'Jäger'", task: true },
        { name: "Karte", Aktion: "Du findest eine Karte des Dschungels. Ab sofort kannst du Karten auch diagonal anlegen.", task: true },
        { name: "Fluss", order: "home", orderText: "Ausgang", Aktion: "Wenn ihr den Weg zum 'Tal der Kannibalen' kennt, könnt ihr mit dem Boot über den Fluss dorthin fahren und den Akt 1 erfolgreich beenden. Lest dann die Karte 'Akt 1 Erfolg'", task: true },
        { name: "Minenfahrt", order: "home", orderText: "Ausgang", Aktion: "Wenn ihr den Weg zum 'Tal der Kannibalen' kennt, alle 4 Höhlen im Spielplan gefunden sind und ihr eine Fackel besitzt, könnt ihr mit einer Lore in das 'Tal der Kannibalen' fahren. Dabei musst du die Fackel abgeben. Verwende in Akt 2 eine Aktionskarte mit 'Mine'", task: true },
        { name: "Sturm", Aktion: "Ein Sturm zieht durch den Dschungel. Er entfernt 2 Macheten vom Spielplan in den Vorrat.", task: true },

    ],
    start: { name: "Akt I", Aktion: "Jane hat den Piloten Jack für eine geheime Expedition in den Dschungel engagiert.  Das Flugzeug stürzt kurz vor dem Ziel ab. Jemand hat die Tanks durchlöchert...", task: true, type: "Startkarte" },
    intro: { name: "Intro", Aktion: "1927, Panama, Die junge Archäologin Jane Smith errreicht den Provinzflughafen St. Josephina. Sie spricht den einzigen verfügbaren Dschungelpiloten Jack Manders an: 'Sie sind ja schon Mittags völlig betrunken. Das ist ja widerlich.' Jack: 'Was?' Jane: 'Ich brauche Sie für einen Flug in den Dschungel. Ich bezahle Sie gut. Also stellen Sie sich unter die Dusche und schlafen ihren Rausch aus. Morgen früh geht es los.' Jack: 'Was?' Jane: 'Los Mann. Stehen Sie auf.' Jack: 'Ok. Ok. Ist ja gut. Morgen früh geht's los.' Das Gespräch wird von einer Person im Hintergrund belauscht. Am nächsten Morgen startet Jacks Flugzeug mit den beiden Richtung undurchdringlichem Dschungel.", task: true, type: "Intro" },
}