var game = {
    cards: [
        { type: "Weg", hor: true, ver: true},
        { type: "Weg", hor: false, ver: true},
        { type: "Weg", hor: true, ver: false},
        { type: "Weg", hor: false, ver: true},
        { type: "Weg", hor: true, ver: false},
        { type: "Tiger", hor: true, ver: false},
        { type: "Falle", hor: false, ver: true},
        { type: "Falle", hor: true, ver: false},
        { type: "Falle", hor: false, ver: true},
        { type: "Falle", hor: true, ver: false},
        { type: "Schlange", hor: true, ver: false},
        { type: "Schlange", hor: false, ver: true},
        { type: "Schlange", hor: true, ver: false},
        { type: "Schlange", hor: false, ver: true},
        { type: "Schlange", hor: true, ver: false},
        { type: "Machete", hor: true, ver: false},
        { type: "Machete", hor: false, ver: true},
        { type: "Machete", hor: true, ver: false},
        { type: "Machete", hor: false, ver: true},
        { type: "Höhle", hor: true, ver: false},
        { type: "Höhle", hor: false, ver: true},
        { type: "Höhle", hor: true, ver: false},
        { type: "Höhle", hor: false, ver: true},
    ],
    start: { type: "Start", hor: false, ver: false},
    end: { type: "Ziel", hor: false, ver: false}
};
