var game = {
    cards: [
        { type: "Weg", hor: true, ver: true, btype: "Tiger", bhor: false, bver: true},
        { type: "Weg", hor: false, ver: true, btype: "Falle", bhor: true, bver: true},
        { type: "Weg", hor: true, ver: false, btype: "Schlange", bhor: true, bver: false},
        { type: "Weg", hor: false, ver: false, btype: "Machete", bhor: false, bver: true},
        { type: "Weg", hor: false, ver: false, btype: "Weg", bhor: false, bver: false},
        { type: "Tiger", hor: true, ver: false, btype: "Weg", bhor: false, bver: true},
        { type: "Tiger", hor: false, ver: true, btype: "Schlange", bhor: false, bver: false},
        { type: "Tiger", hor: true, ver: true, btype: "Höhle", bhor: false, bver: true},
        { type: "Hütte", hor: false, ver: false, btype: "Hütte", bhor: true, bver: false},
        { type: "Falle", hor: true, ver: false, btype: "Tiger", bhor: false, bver: true},
        { type: "Falle", hor: false, ver: true, btype: "Weg", bhor: false, bver: false},
        { type: "Falle", hor: false, ver: false, btype: "Machete", bhor: false, bver: true},
        { type: "Falle", hor: true, ver: true, btype: "Schlange", bhor: false, bver: true},
        { type: "Schlange", hor: true, ver: false, btype: "Tiger", bhor: false, bver: true},
        { type: "Schlange", hor: false, ver: true, btype: "Weg", bhor: true, bver: false},
        { type: "Schlange", hor: false, ver: false, btype: "Machete", bhor: false, bver: false},
        { type: "Schlange", hor: true, ver: true, btype: "Machete", bhor: true, bver: true},
        { type: "Machete", hor: true, ver: false, btype: "Tiger", bhor: false, bver: true},
        { type: "Machete", hor: false, ver: true, btype: "Weg", bhor: true, bver: false},
        { type: "Machete", hor: true, ver: true, btype: "Weg", bhor: true, bver: false},
        { type: "Machete", hor: false, ver: false, btype: "Höhle", bhor: false, bver: true},
        { type: "Höhle", hor: true, ver: false, btype: "Weg", bhor: false, bver: false},
        { type: "Höhle", hor: false, ver: true, btype: "Tiger", bhor: true, bver: false},
    ],
    start: { type: "Start", hor: false, ver: false, btype: "Start", bhor: false, bver: false, open: true},
    end: { type: "Ziel", hor: false, ver: false,btype: "Ziel", bhor: false, bver: false, open: true}
};
